# Generated by Django 4.2.1 on 2023-05-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('quantidade_em_estoque', models.PositiveIntegerField(default=0)),
                ('sabor', models.CharField(choices=[('chocolate', 'Chocolate'), ('morango', 'Morango'), ('baunilha', 'Baunilha'), ('sem_sabor', 'Sem sabor')], max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='media/produtos/%Y/%m/%d')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
    ]
