# Generated by Django 4.2 on 2023-04-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estoques', to='estoque.estoque')),
            ],
        ),
    ]
