# Generated by Django 4.2 on 2023-04-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='produtos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='produto',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_em_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.AddField(
            model_name='marca',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estoques', to='estoque.produto'),
        ),
    ]
