# Generated by Django 4.2 on 2023-04-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_marca_remove_produto_estoque_remove_produto_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quantidade',
            new_name='Marca',
        ),
    ]
