# Generated by Django 4.2 on 2023-04-23 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_rename_quantidade_produto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Marca',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.marca'),
            preserve_default=False,
        ),
    ]
