# Generated by Django 4.2 on 2023-04-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_marca_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sabor',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('morango', 'Morango'), ('baunilha', 'Baunilha'), ('sem_sabor', 'Sem sabor')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
