# Generated by Django 4.2 on 2023-04-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_marca_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sabor',
            field=models.CharField(blank=True, choices=[('morango', 'Morango'), ('chocolate', 'Chocolate'), ('baunilha', 'Baunilha'), ('sem-sabor', 'Sem sabor')], max_length=20),
        ),
    ]
