# Generated by Django 4.2 on 2023-05-04 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_produto_sabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='media/produtos/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.imagem'),
        ),
    ]
