# Generated by Django 4.2.1 on 2023-05-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_carrinho_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular'),
        ),
    ]
