# Generated by Django 4.2 on 2023-05-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='aberto', max_length=20),
        ),
    ]
