# Generated by Django 4.2 on 2023-05-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='preco_unitario',
        ),
    ]
